# coding: utf-8

"""
    Car Rental API

    API for managing car rentals

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.rentals_api import RentalsApi


class TestRentalsApi(unittest.TestCase):
    """RentalsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = RentalsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_rental_rentals_rental_id_delete(self) -> None:
        """Test case for cancel_rental_rentals_rental_id_delete

        Cancel Rental
        """
        pass

    def test_get_rental_rentals_rental_id_get(self) -> None:
        """Test case for get_rental_rentals_rental_id_get

        Get Rental
        """
        pass

    def test_get_rentals_rentals_get(self) -> None:
        """Test case for get_rentals_rentals_get

        Get Rentals
        """
        pass


if __name__ == '__main__':
    unittest.main()
