# coding: utf-8

"""
    Car Rental API

    API for managing car rentals

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.car_create import CarCreate

class TestCarCreate(unittest.TestCase):
    """CarCreate unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> CarCreate:
        """Test CarCreate
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `CarCreate`
        """
        model = CarCreate()
        if include_optional:
            return CarCreate(
                make = '',
                model = '',
                year = 56,
                daily_rate = 1.337
            )
        else:
            return CarCreate(
                make = '',
                model = '',
                year = 56,
                daily_rate = 1.337,
        )
        """

    def testCarCreate(self):
        """Test CarCreate"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
