# coding: utf-8

"""
    Car Rental API

    API for managing car rentals

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.car import Car

class TestCar(unittest.TestCase):
    """Car unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Car:
        """Test Car
            include_optional is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Car`
        """
        model = Car()
        if include_optional:
            return Car(
                make = '',
                model = '',
                year = 56,
                daily_rate = 1.337,
                id = 56,
                available = True
            )
        else:
            return Car(
                make = '',
                model = '',
                year = 56,
                daily_rate = 1.337,
                id = 56,
                available = True,
        )
        """

    def testCar(self):
        """Test Car"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
